# Lie about language support for broader support
language: c

sudo: false

branches:
    only:
        - develop
        - feature/travis

env:
    global:
        - LUAROCKS=2.2.2
    matrix:
        - LUA=luajit2.1
        - LUA=luajit2.0
        - LUA=luajit
        - LUA=lua5.3
        - LUA=lua5.2
        - LUA=lua5.1

before_install:
    - source .travis/setenv_lua.sh
    - luarocks install busted

script:
    - luarocks make rockspecs/luaevent/luaevent-scm-0.rockspec
    - cd test && busted event_buffer-tests.lua

notifications:
    email:
        on_success: change
        on_failure: always
